# Generated by Django 5.0.4 on 2024-04-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Rooms_available', models.IntegerField()),
                ('price', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
