# Generated by Django 5.0.4 on 2024-04-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_for_rent', '0002_listing_availableby'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to='listing_images/'),
            preserve_default=False,
        ),
    ]
