# Generated by Django 5.0.4 on 2024-04-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties_for_rent', '0003_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
